# Generated by Django 3.2 on 2021-05-07 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GachaAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('weight', models.IntegerField(verbose_name='重み')),
                ('rarity', models.CharField(choices=[('SSR', 'SSR'), ('SR', 'SR'), ('R', 'R')], default='R', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'db_table': 'gacha',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='名前')),
                ('orbs', models.IntegerField(verbose_name='オーブ')),
            ],
        ),
    ]
