# Generated by Django 3.2 on 2021-05-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
