# Generated by Django 3.2 on 2021-05-07 17:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('0', '通常ガチャ'), ('1', '10連ガチャ(SR以上確定)'), ('2', '10連ガチャ(SSR確定)')], default='0', max_length=20, verbose_name='ガチャ種類')),
                ('result', jsonfield.fields.JSONField()),
            ],
            options={
                'db_table': 'gacha_result',
            },
        ),
        migrations.AlterField(
            model_name='gachaadmin',
            name='rarity',
            field=models.CharField(choices=[('SSR', 'SSR'), ('SR', 'SR'), ('R', 'R')], default='R', max_length=8, verbose_name='レア度'),
        ),
    ]
