# Generated by Django 3.2 on 2021-05-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0004_remove_gacha_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gacha',
        ),
    ]
