# Generated by Django 3.2 on 2021-05-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0006_gacha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gacha',
        ),
    ]
