# Generated by Django 3.2 on 2021-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0007_delete_gacha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gachaadmin',
            name='choice',
            field=models.CharField(choices=[('0', '通常ガチャ'), ('1', '10連ガチャ(SR以上確定)'), ('2', '10連ガチャ(SSR確定)')], default='0', max_length=20, verbose_name='ガチャ種類'),
        ),
    ]
