# Generated by Django 3.2 on 2021-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0008_gachaadmin_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gachaadmin',
            name='choice',
        ),
    ]
